### ISSUE TITLE
Adding a /healthz method

### ISSUE THREAD

**Issue by alexmbird** [claws/aioprometheus#18]
There are cases where aioprometheus will be the only http-serving port an application has, and in these instances it's helpful to use it for an orchestrator (AWS ECS, Kubernetes etc) to check the application's health.

Now it tolerates the lack of an `Accept:` header it's possible to use `/metrics` for this.  But generating the textual metrics list only to throw the output away is somewhat wasteful.

To help out in this case would you be open to a PR adding a `/healthz` method that does nothing but return a 200 code?

**Comment by claws** [comment]
Sure, that should be pretty straight forward.

**Comment by claws** [comment]
I am going to assume that your PR #19 indirectly closes this issue.

**Comment by alexmbird** [comment]
Yes it does.  Thank you.
