### ISSUE TITLE
Aiohttp 3+ start/shutdown changes

### ISSUE THREAD

**Issue by hellysmile** [claws/aioprometheus#24]
Hey, aiohttp3 introduced advanced site runners https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners

I am going to make PR to adjust aioprometheus to use it, but it will force to support aiohttp3+. Is it acceptable for You @claws ?

**Comment by hellysmile** [comment]
Cool, I will test lates changes today, thnx

**Comment by hellysmile** [comment]
Master work good for me!

I have suggestion

https://github.com/claws/aioprometheus/blob/master/src/aioprometheus/service.py#L152

should have small `shutdown_timeout`, otherwise it can stuck for default is too big for real prometheus usage 

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_runner.py#L63

What about to make it 2 sec for example?

**Comment by claws** [comment]
Great. 

Your suggestion regarding shutdown timeout sounds good.

**Comment by hellysmile** [comment]
I have small PR for this https://github.com/claws/aioprometheus/pull/25 , lets move further conversation there
