### ISSUE TITLE
Histograms are not compatible with prometheus histogram_quantile() 

### ISSUE THREAD

**Issue by dimitar-petrov** [claws/aioprometheus#28]
Prometheus histograms are meant to be cumulative. In addition the format specifies that buckets should be ordered so +Inf should be last and +Inf should match _count.

More information can be found here: https://github.com/prometheus/prometheus/issues/4264

**Comment by claws** [comment]
Thanks for letting me know about this issue.  I'm away from home right now, but will look into this soon.
