### ISSUE TITLE
Make protocol-buffer optional

### ISSUE THREAD

**Issue by hellysmile** [claws/aioprometheus#41]
As https://github.com/prometheus/docs/pull/972/files 

`Prometheus 2.0 removed support for the protocol-buffer format
and only supports the text-based format.`

would be nice to make `protocol-buffer` as optional dependency

@claws if you like the idea I'll be happy to make pull request

something like

`pip aioprometheus[protoc]`

**Comment by claws** [comment]
Sure, I'm open to that.
