### ISSUE TITLE
[BUG] Multiple decorator bug

### ISSUE THREAD

**Issue by grootg** [claws/aioprometheus#47]
While using inprogress and count_exceptions inprogress doesn't reach the metric.dec call
Suggested fix (for inprogress):

`        @wraps(func)
        async def func_wrapper(*args, **kwds):
            try:
                metric.inc(labels)
                rv = func(*args, **kwds)
                if isinstance(rv, asyncio.Future) or asyncio.iscoroutine(rv):
                    rv = await rv
            finally:
                metric.dec(labels)
            return rv
`

**Comment by claws** [comment]
Thanks for the feedback, I'll look into your suggested fix.

**Comment by claws** [comment]
Fixed in #55
