### ISSUE TITLE
Documentation seems to be outdated

### ISSUE THREAD

**Issue by giffels** [claws/aioprometheus#63]
Dear all,

the [example](https://aioprometheus.readthedocs.io/en/latest/#example) is showing an outdated example due to the recent changes to the API, that introduced automatic registeration of metrics when they are created. Could you adjust the documentation accordingly?

Thanks,
Manuel

**Comment by claws** [comment]
I did update the documentation in line with the new API but it looks like the readthedocs site is not updating to show the latests docs. I'll look into it.

**Comment by claws** [comment]
Docs are finally updated.
