### ISSUE TITLE
Missing Service in aioprometheus

### ISSUE THREAD

**Issue by marekpow** [claws/aioprometheus#64]
I think something is wrong with your library

![image](https://user-images.githubusercontent.com/7034666/134811196-e1e1da57-cd88-43ad-8b81-d42dcafd6162.png)

Could you please help me with that problem?

Marek

**Comment by claws** [comment]
Yeah, API has been updated so that the service now needs to be imported explicitly. Then I'm guessing dump1090exporter does not pin the requirement so is pulling in this latest version. I'll look into it.

**Comment by claws** [comment]
This is an issue in the dump1090-exporter package, not a problem in aioprometheus. Closing.
