### ISSUE TITLE
Middleware attempts to create conflicting Counters if not added last

### ISSUE THREAD

**Issue by JacobHenner** [claws/aioprometheus#72]
In Starlette, every middleware class that has been added to an application is called [each time an additional middleware class is added](https://github.com/encode/starlette/blob/52c4a78104a8ea73a7546985b243026158a45a4b/starlette/applications.py#L97-L98).

Unless aioprometheus's MetricsMiddleware is added as the last piece of middleware, it's `__init__(...)` will be called more than once. This causes an Exception when the Counter metrics are redefined with the same name in the same registry.

**Comment by claws** [comment]
Hmm, yeah looks that way. 
I'll look into developing a solution to this problem.

**Comment by claws** [comment]
Thanks for reporting issue. Hopefully fixed in latest 22.3.0 release.
