### ISSUE TITLE
websocket support in quart

### ISSUE THREAD

**Issue by l1f** [claws/aioprometheus#93]
I ran into a problem with `MetricsMiddleware` today, as soon as I add that to my Quart project websockets don't work anymore. 

I think the problem should be easy to solve, in that when the scope is checked, not only `http` may be used, but also `websocket`.

**Comment by Klavionik** [comment]
Having the same issues with WebSockets. 😢

**Comment by l1f** [comment]
I would also be happy if it get merged. But so far I haven't heard anything from the maintainer.
